### ISSUE TITLE
Minimum Ruby/Redmine requirement?

### ISSUE THREAD

**Issue by nebojsac** [sciyoshi/redmine-slack#84]
I tried settings this up on an older version, and kept gettings a 500 internal error until I disabled it. So this might not be a code issue, but I don't know what the minimum requirements are. If possible, would be good to update the README with this info. I used: 
Redmine 1.0.0
gem --version: 1.3.5

When the plugin is active, I get a 500 internal error, and this is the stack trace:
```

NoMethodError (undefined method `is_private?' for #<Issue:0x7f0f677be7b0>):
  lib/redmine/hook.rb:63:in `send'
  lib/redmine/hook.rb:63:in `call_hook'
  lib/redmine/hook.rb:63:in `each'
  lib/redmine/hook.rb:63:in `call_hook'
  lib/redmine/hook.rb:60:in `call_hook'
  app/models/issue.rb:507:in `save_issue_with_child_records'
  app/models/issue.rb:487:in `save_issue_with_child_records'
  app/controllers/issues_controller.rb:181:in `update'
  passenger (2.2.15) lib/phusion_passenger/rack/request_handler.rb:92:in `process_request'
  passenger (2.2.15) lib/phusion_passenger/abstract_request_handler.rb:207:in `main_loop'
  passenger (2.2.15) lib/phusion_passenger/railz/application_spawner.rb:441:in `start_request_handler'
  passenger (2.2.15) lib/phusion_passenger/railz/application_spawner.rb:381:in `handle_spawn_application'
  passenger (2.2.15) lib/phusion_passenger/utils.rb:252:in `safe_fork'
  passenger (2.2.15) lib/phusion_passenger/railz/application_spawner.rb:377:in `handle_spawn_application'
  passenger (2.2.15) lib/phusion_passenger/abstract_server.rb:352:in `__send__'
  passenger (2.2.15) lib/phusion_passenger/abstract_server.rb:352:in `main_loop'
  passenger (2.2.15) lib/phusion_passenger/abstract_server.rb:196:in `start_synchronously'
  passenger (2.2.15) lib/phusion_passenger/abstract_server.rb:163:in `start'
  passenger (2.2.15) lib/phusion_passenger/railz/application_spawner.rb:222:in `start'
  passenger (2.2.15) lib/phusion_passenger/spawn_manager.rb:253:in `spawn_rails_application'
  passenger (2.2.15) lib/phusion_passenger/abstract_server_collection.rb:126:in `lookup_or_add'
  passenger (2.2.15) lib/phusion_passenger/spawn_manager.rb:247:in `spawn_rails_application'
  passenger (2.2.15) lib/phusion_passenger/abstract_server_collection.rb:80:in `synchronize'
  passenger (2.2.15) lib/phusion_passenger/abstract_server_collection.rb:79:in `synchronize'
  passenger (2.2.15) lib/phusion_passenger/spawn_manager.rb:246:in `spawn_rails_application'
  passenger (2.2.15) lib/phusion_passenger/spawn_manager.rb:145:in `spawn_application'
  passenger (2.2.15) lib/phusion_passenger/spawn_manager.rb:278:in `handle_spawn_application'
  passenger (2.2.15) lib/phusion_passenger/abstract_server.rb:352:in `__send__'
  passenger (2.2.15) lib/phusion_passenger/abstract_server.rb:352:in `main_loop'
  passenger (2.2.15) lib/phusion_passenger/abstract_server.rb:196:in `start_synchronously'

```

I tried upgrading Ruby/Redmine, but gave up because I lack experience there and kept running into new problems.

**Comment by sciyoshi** [comment]
@nebojsac I haven't tested this plugin on Redmine < 3.2, but pull requests are welcome for adding backwards compatibility.

**Comment by miguelfspinto** [comment]
is this plugin compatible with redmine 4.x
