### ISSUE TITLE
Where's version 0.2...?

### ISSUE THREAD

**Issue by cmartear** [sciyoshi/redmine-slack#91]
git clones 0.1

**Comment by sciyoshi** [comment]
@cmartear thanks for the heads up, I never bumped the version in Git.

**Comment by cmartear** [comment]
Thanks, but I'm not sure if this bug (previously reported) was solved...

~~~
Started GET "/issues/32" for 200.42.13.194 at 2016-07-20 18:35:25 -0300
Processing by IssuesController#show as HTML
  Parameters: {"id"=>"32"}
  Current user: cmiranda (id=5)
  Rendered issues/_action_menu.html.erb (5.8ms)
  Rendered issue_relations/_form.html.erb (2.3ms)
  Rendered issues/_relations.html.erb (3.5ms)
  Rendered issues/_history.html.erb (15.4ms)
  Rendered issues/_action_menu.html.erb (6.2ms)
  Rendered issues/_form_custom_fields.html.erb (0.2ms)
  Rendered issues/_attributes.html.erb (13.5ms)
  Rendered issues/_form.html.erb (32.1ms)
  Rendered attachments/_form.html.erb (3.2ms)
  Rendered issues/_edit.html.erb (41.6ms)
  Rendered issues/_sidebar.html.erb (3.2ms)
  Rendered watchers/_watchers.html.erb (4.0ms)
  Rendered issues/show.html.erb within layouts/base (270.6ms)
Completed 200 OK in 383ms (Views: 287.3ms | ActiveRecord: 28.9ms)
Started POST "/projects/vodgc/issues" for x.x.x.x at 2016-07-20 18:35:27 -0300
Processing by IssuesController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX==", "form_update_triggered_by"=>"", "issue"=>{"is_private"=>"0", "tracker_id"=>"1", "subject"=>"test issue", "description"=>"se va  borrar", "status_id"=>"1", "priority_id"=>"2", "assigned_to_id"=>"", "fixed_version_id"=>"", "parent_issue_id"=>"", "start_date"=>"2016-07-20", "due_date"=>""}, "was_default_status"=>"1", "commit"=>"Create", "project_id"=>"vodgc"}
  Current user: cmiranda (id=5)
  Rendered mailer/_issue.text.erb (3.0ms)
  Rendered mailer/issue_add.text.erb within layouts/mailer (3.9ms)
  Rendered mailer/_issue.html.erb (2.1ms)
  Rendered mailer/issue_add.html.erb within layouts/mailer (2.6ms)
Completed 500 Internal Server Error in 139ms (ActiveRecord: 24.4ms)

NameError (undefined local variable or method `logger' for #<SlackListener:0x007efdad0165b0>):
  plugins/redmine_slack/lib/redmine_slack/listener.rb:158:in `rescue in speak'
  plugins/redmine_slack/lib/redmine_slack/listener.rb:152:in `speak'
  plugins/redmine_slack/lib/redmine_slack/listener.rb:37:in `controller_issues_new_after_save'
  lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
  lib/redmine/hook.rb:61:in `each'
  lib/redmine/hook.rb:61:in `block in call_hook'
  lib/redmine/hook.rb:58:in `tap'
  lib/redmine/hook.rb:58:in `call_hook'
  lib/redmine/hook.rb:91:in `call_hook'
  app/controllers/issues_controller.rb:141:in `create'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

~~~
